version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
       POSTGRES_USERNAME: postgres
       POSTGRES_PASSWORD: my_password
       POSTGRES_DATABASE: my_database
    networks:
    - tasknetwork

networks:
  tasknetwork:
    